### ISSUE TITLE
Responsive Ads: How to Handle?

### ISSUE THREAD

**Issue by regnyc** [OpenDirect/Spec-Review#20]
As the industry moves towards HTML5 creative (Flash is obsolete), more creative will be designed to be responsive. 

I realize this is a version one, but there is one thing that must be added into version one under 'Size', and that is a 'Responsive' category. 

At the moment a height and width is required, but Responsive ads adjust to different heights and widths (eg full page interstitials are 100% height and width of the device's screen resolution, and there are 180+ device screen resolutions, and 10 major aspect ratios (16:9, 4:3, 3:2 etc).

So as a baseline - the ad size needs to be defined as either 1) 'fixed' or 2) 'responsive'. If a 'fixed' size, then height and width is required. If 'responsive' we need a set of other options that will be passed. Possible ideas could be around...
1) Screen Sizes (eg Small (smartphones > 7"), Medium (7">20"), Large (20"+). 
2) Aspect Ratios (eg Portrait or Landscape, 16x9, 9x16 etc).

Unfortunately we can't have an industry API spec that holds back the industry's future via HTML5 creative. If there is no HTML5 creative solution, then the industry will struggle to thrive as Flash support moves towards 0%.

**Comment by MelissaIAB** [comment]
We will not support this OpenDirect 2.0 due to lack of demand and support needed for other formats such as video.  Putting this on hold for possible support in in OpenDirect 3.0.

**Comment by MartinDesigner** [comment]
Hey! You have written that need to create responsive ads and inject into your website content as html because You need to handle responsive. I know perfect solution for You - how to easily design responsive ads from predesigned templates and embed them into any html site including outstanding auto-responsive on output without writing any code. This is it (agile description of app which about I'm telling about):
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, I propose you to try and explore this amazing free app for visual online designing and online publishing. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi
