### ISSUE TITLE
Currency property missing in ProductAvailsSearch object

### ISSUE THREAD

**Issue by harshal10** [OpenDirect/Spec-Review#34]
In order to identify the currency in which publisher should respond (for rates) we need currency as an input property of ProductAvailsSearch object.

**Comment by MelissaIAB** [comment]
Can build spec for allowable multiple products per currency and allow user to chose currency. If publisher doesn't support that, has to return product per currency.  
*working session item*

**Comment by MelissaIAB** [comment]
From the economist: we should also put in a caveat that banking details to the right accounts in those currencies would need to be supported.

**Comment by MelissaIAB** [comment]
@harshal10 - do you have any updates on whether the proposed fix will work for Microsoft?

Add add optional property search - May have one product associated with 5 currencies. Publisher would pass back 5 different products.

**Comment by katiestroudpro** [comment]
Added to what is now section 2.4.2 with description: The currency the product supports. If the publisher supports the option to filter product avails by currency, then only products that support select currency is returned. Otherwise, publisher returns duplicate product avails, each with different supported currencies. 

Data type is a string and pub support is recommended.
