### ISSUE TITLE
Draft 1.5 - Clarification needed : who creates accounts ?

### ISSUE THREAD

**Issue by ghost** [OpenDirect/Spec-Review#69]
Reading the specs, it's not clear at all
- p8 publisher create accounts for buyers : “Publishers create accounts for buyers to access in any OpenDirect system which the publisher has a working relationship”
- p10 buyer, if agency and given right by the advertiser, can create accounts “Before an agency may create accounts and perform buys on behalf of the advertiser, the advertiser must give permissions to the agency”
- p97 buyer (agency or advertiser) create accounts : “Create an Account using your Organization ID as the BuyerID and the advertiser’s organization ID as the AdvertiserID”
- p52 if agency, the buyer cannot create accounts, advertiser must do it : “an agency may not add accounts to an advertiser’s organization. If an advertiser wants an agency to manage an account on their behalf, the advertiser must add the account and set the account’s buyerId to the agency’s organization ID.”
- p52 buyer, if advertiser, can create accounts : “and then create accounts for each brand, subsidiary, or division”

**Comment by robynp** [comment]
It is a little ambiguous in part due to account being used as both the _“User”_ account and _Account_ object and a lack of clarity around the Account access rules.

My understanding is:
-   The Seller always creates Organisations (outside OpenDirect)
-   The Seller creates one or more UserAccounts for the Organisation (outside OpenDirect)
-   The Seller determines which other Organisations each UserAccount can access.
-   The UserAccount can create an Account using any Organisations it has access to subject to the following rules:
  -   The UserAccount is a Advertiser
  -   The UserAccount has “Create Account” privileges 
-   The UserAccount can access any Account it has created.
-   The UserAccount can access any Account where its Organisation is the BuyerId of the Account
-   The Seller may also create Accounts and set the BuyerId to an Agency Organisation (outside OpenDirect)

**Comment by MelissaIAB** [comment]
We will create FAQ of on-boarding set-up that includes the communication of IDs for known entities.
