### ISSUE TITLE
Draft 1.5 - Clarification needed : PackageOnly

### ISSUE THREAD

**Issue by ghost** [OpenDirect/Spec-Review#71]
Reading the description, we don't understand what PackageOnly mean

**Comment by aruckoj** [comment]
Due to OpenDirect 1.5 Draft:
- (page 7) Publishers often create orders on behalf of their clients.
  Features for summarizing line booking statuses, product package only deals, and order
  expiration date have been added to support publisher order creation.
- (page 21) PackageOnly: Identifies whether the order is only available as a package or if specific items can be separated from the inventory. A value of TRUE means the inventory is only available as a package. A value of FALSE allows the buyer to select specific items from inventory.

From these I assume that PackageOnly is useful only if you create Order as a publisher. In that case PackageOnly=true means that you're ready to provide this order only as a whole. In other case, you're ready to sell each line individually or reorder them in some way.

**Comment by ghost** [comment]
Thanks for the update Aleksej

To be sure we understand correctly, when the spec states "Publishers often create orders on behalf of their clients", does it mean that OpenDirect v1.5 also handle the RFP process ?
That is : when the buyer has a brief (custom need), instead of selecting some products from the publisher catalog directly in his buying platform, he will inform the publisher about his brief so that the publisher create a custom order for this brief.

Then, PackageOnly would mean that lines in the order are not derived from products (custom need) ?! 
If it's the case, the workflow is not clear for us (and ProductId is required in a line)

**Comment by aruckoj** [comment]
I can find no mentions of RFP in current draft.
Presumably in some OpenDirect implementations a publisher can create Order on behalf of an agency upon direct request (e.g. via phone or email).
Probably someone who is more aware can clarify this question.

**Comment by MelissaIAB** [comment]
That is correct. In some implementations, publishers can create an order on behalf of the agency/client upon direct request.

**Comment by ghost** [comment]
But the lines would be for custom needs and not necessarily attached to products (would make sense) ?
Thanks

**Comment by MelissaIAB** [comment]
They would be attached to the products. The decision was made to add this feature due to current industry trends where most deals are still made over the phone and through email and not always via the platform.

**Comment by MelissaIAB** [comment]
Will develop some explanatory text around this in the FAQs.

**Comment by ghost** [comment]
I created another issue for the RFP workflow : https://github.com/OpenDirect/Spec-Review/issues/79
Would be very interesting for v2
