### ISSUE TITLE
Draft 1.5 - Clarification needed : "UserAccount" purpose

### ISSUE THREAD

**Issue by ghost** [OpenDirect/Spec-Review#81]
Following @robynp comment on https://github.com/OpenDirect/Spec-Review/issues/69, could we give some guidance on what cases the publisher has to deal with for "UserAccount" ?

Options
1. One and only one "UserAccount" for buyer organizations (0 or 1 "UserAccount" if the organization is never the buyer)
2. One or more "UserAccount" for buyer organizations (0, 1 or more "UserAccount" if the organization is never the buyer), with the same user rights for each "UserAccount"
3. One or more "UserAccount" for buyer organizations (0, 1 or more "UserAccount" if the organization is never the buyer), with the different user rights for each "UserAccount"

Obviously, option 1 is the easiest to implement for publishers : would it be OK ?
Option 2 would help when people change jobs (so they won't have access anymore)
Option 3 would enable use cases like : Alice & Bob both work for Vivaki, Alice has rights on Coca organization & accounts (and not Pepsi), Bob has rights on Pepsi organization & accounts (and not Coca). Is it needed by AG buying platforms ?

Reading the specs, we understand that it's up to the publisher to make the call, but it would be great to gather some feedback & guidance from the committee

**Comment by aroslov** [comment]
UserAccount in this case is purely an "API account" - credentials to make API calls via OAuth. Assuming that API calls are programmatic and not carried out by humans, for most cases you only need a single set of credentials per buying entity. The rest is handled by whatever system is used on top of OpenDirect (e.g. a trading desk user interface with separate logins for agency employees and advertisers). 

So I'd suggest this issue is not in scope of OpenDirect, except to define that:
- Publisher must support at least one "full access" user account (API credentials) per buying organisation
- Non-buying organisations may have user accounts, but its optional
- Publisher may support flexible permission schemes for additional user accounts

**Comment by robynp** [comment]
Need to clarify the difference (if any) between users and API users
